;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-defun
        beginning-of-visual-line
        end-of-visual-line
        indent-for-tab-command
        keyboard-escape-quit
        kill-visual-line
        mouse-drag-vertical-line
        mouse-select-window
        ns-copy-including-secondary
        org-cycle
        org-delete-char
        org-force-self-insert
        org-metaleft
        org-metaright
        org-metaup
        org-return
        org-self-insert-command
        org-table-copy-down
        org-yank
        paredit-semicolon
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-find-file
        ))
